### PR TITLE
[runtime] surport tlg lm

### PR DESCRIPTION
**Pull request by robin1001**

### CODE REVIEW

**Comment by mikelei** [comment]
Better to add a unit test for decoding.

**Comment by robin1001** [comment]
> Better to add a unit test for decoding.

okay, we will try to add it later. 
it's a draft PR and it's still in early stage now. it will be separated into several small PRs once it is ready.

**Comment by Mddct** [comment]
If we regard blank as sil, then the timestamp can be obtained by decoding in wfst, so there is no need to call ctcendpoint afterwards?

**Comment by robin1001** [comment]
> If we regard blank as sil, then the timestamp can be obtained by decoding in wfst, so there is no need to call ctcendpoint afterwards?

It's more flexible to keep decoder and endpoint independent.

**Pull request closed without merging**
