### PR TITLE
support subword prefix specific

### PR DESCRIPTION
**Pull request by Mddct**
user can specific subword prefix such as "##" or "_"

### CODE REVIEW

**Comment by robin1001** [comment]
What symbol do you use for space?

**Comment by Mddct** [comment]
I use ”##”。 Because spm can denote a space indicator, and bert tokensize also use ##。

For example：

他非常friendly -> 他 非 常 ##fri end ly

**Comment by robin1001** [comment]
Please note this logic suppose only one UTF8 character "▁" (U+2581) is used to denote <space>,  If there are more than one character, it may gives wrong result.

for example, ## is used for space,  then both ## and # will be replaced to blank.

I think maybe you can just replace ## with "▁ " in your symbol table file.

**Comment by Mddct** [comment]
It's an easy way. then I close this pr. Thanks

**Pull request closed without merging**
